on:
  push:
    tags:
      - "*"

env:
  CARGO_TERM_COLOR: always

permissions:
  id-token: write
  contents: read
  attestations: write

name: Build & Release
jobs:
  build:
    name: ${{ matrix.name }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: linux-amd64
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - name: linux-amd64-musl
            runner: ubuntu-latest
            target: x86_64-unknown-linux-musl
            musl: true
          - name: linux-arm64
            runner: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
          - name: linux-arm64-musl
            runner: ubuntu-24.04-arm
            target: aarch64-unknown-linux-musl
            musl: true
          - name: macos-amd64
            runner: macos-latest
            target: x86_64-apple-darwin
          - name: macos-arm64
            runner: macos-latest
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@master
      - name: "Install musl dependencies" # https://blog.davidvassallo.me/2021/06/10/lessons-learned-building-statically-linked-rust-binaries-openssl/
        run: "sudo apt update && sudo apt install -y pkg-config musl-tools libssl-dev"
        if: matrix.musl
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          target: ${{ matrix.target }}

      - name: Build
        uses: clechasseur/rs-cargo@v3
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: "target/${{ matrix.target }}/release/ha-tkpd"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@master
        with:
          name: ha-tkpd-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/ha-tkpd

  release:
    name: Create release
    needs: build
    runs-on: "ubuntu-latest"
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
      - name: Create a Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ha-tkpd-tracker/ha-tkpd-aarch64-apple-darwin
            ha-tkpd-tracker/ha-tkpd-x86_64-apple-darwin
            ha-tkpd-tracker/ha-tkpd-x86_64-unknown-linux-gnu
            ha-tkpd-tracker/ha-tkpd-x86_64-unknown-linux-musl
            ha-tkpd-tracker/ha-tkpd-aarch64-unknown-linux-gnu
            ha-tkpd-tracker/ha-tkpd-aarch64-unknown-linux-musl
